import { ClerkProvider } from "@clerk/nextjs";
import { type Metadata } from "next";
import { Inter } from 'next/font/google';

import "~/styles/globals.css";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create-t3-app",
  icons: "/favicon.ico",
};

export default function RootLayout({
  // Layouts must accept a children prop.
  // This will be populated with nested layouts or pages
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
